version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis
    networks:
      - internal
  nginx:
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - internal
      - external
    depends_on:
      - web
  web:
    build:
      context: web
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-MCBingo.settings_prod}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOST=localhost
    networks:
      - internal
    depends_on:
      - db
      - redis

networks:
  internal:
    name: bingo_internal
  external:
    name: bingo_external

volumes:
  postgres_data:
