version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis
    networks:
      - internal
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - frontend_static:/frontend/
    ports:
      - "8000:8000"
    networks:
      - internal
      - external
    depends_on:
      - web
      - frontend
  web:
    build:
      context: web
#    volumes:
#      - frontend_static:/frontend  # Not necessary with no frontend
    networks:
      - internal
    depends_on:
      - db
      - redis
  frontend:
    build:
      context: frontend
    volumes:
      - frontend_static:/frontend/build/

networks:
  internal:
    name: bingo_internal
  external:
    name: bingo_external

volumes:
  frontend_static:
  postgres_data:
