version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis
    networks:
      - internal
  nginx:
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - internal
      - external
    depends_on:
      - web
  web:
    build:
      context: web
#    volumes:
#      - frontend_static:/frontend  # Not necessary with no frontend
    networks:
      - internal
    depends_on:
      - db
      - redis

networks:
  internal:
    name: bingo_internal
  external:
    name: bingo_external

volumes:
  postgres_data:
