# Generated by Django 3.1.6 on 2021-04-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_yamlify'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerboardmarking',
            name='announced',
            field=models.BooleanField(default=False),
        ),
    ]
