version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend
  redis:
    image: redis
    networks:
      - backend
  web:
    build:
      context: ..
      dockerfile: web/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend
    depends_on:
      - db
      - redis
networks:
  backend:
    name: bingo_backend
  frontend:
    name: bingo_frontend
